#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-server
  namespace: #@ data.values.NAMESPACE
  annotations:
    #! This Secret is versioned, since we want to restart pods which rely
    #! on this object when there's an update.
    kapp.k14s.io/versioned: ""
stringData:
  ALLOW_EMPTY_PASSWORD: "yes"
